# Lore are checked without color codes.
# If you insert a color code inside this config, the plugin stop working.
block-lore:
  - 'Blocked totem'
  - 'Second lore blocked'

# Define if you want te message about the protection to be displayed or not
blocked-message: true